# Initially auto-generated by compose2nix.

{ pkgs, lib, config, self, ... }:

{
  age.secrets.authentik = {
    file = "${self}/secrets/authentik.env.age";
    mode  = "400";
  };
  
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."authentik-postgresql" = {
    image = "docker.io/library/postgres:16-alpine";
    environmentFiles = [
      config.age.secrets.authentik.path
    ];
    volumes = [
      "authentik_database:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -d \${POSTGRES_DB} -U \${POSTGRES_USER}"
      "--health-interval=30s"
      "--health-retries=5"
      "--health-start-period=20s"
      "--health-timeout=5s"
      "--network-alias=postgresql"
      "--network=authentik_default"
    ];
  };
  systemd.services."podman-authentik-postgresql" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-authentik_default.service"
      "podman-volume-authentik_database.service"
    ];
    requires = [
      "podman-network-authentik_default.service"
      "podman-volume-authentik_database.service"
    ];
    partOf = [
      "podman-compose-authentik-root.target"
    ];
    wantedBy = [
      "podman-compose-authentik-root.target"
    ];
  };
  virtualisation.oci-containers.containers."authentik-server" = {
    image = "ghcr.io/goauthentik/server:2026.2.0";
    environmentFiles = [
      config.age.secrets.authentik.path
    ];
    volumes = [
      "/var/lib/authentik/custom-templates:/templates:rw"
      "/var/lib/authentik/data:/data:rw"
    ];
    ports = [
      "9080:9000/tcp"
      "9443:9443/tcp"
    ];
    cmd = [ "server" ];
    dependsOn = [
      "authentik-postgresql"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=server"
      "--network=authentik_default"
      "--shm-size=536870912"
    ];
  };
  systemd.services."podman-authentik-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-authentik_default.service"
    ];
    requires = [
      "podman-network-authentik_default.service"
    ];
    partOf = [
      "podman-compose-authentik-root.target"
    ];
    wantedBy = [
      "podman-compose-authentik-root.target"
    ];
  };
  virtualisation.oci-containers.containers."authentik-worker" = {
    image = "ghcr.io/goauthentik/server:2026.2.0";
    environmentFiles = [
      config.age.secrets.authentik.path
    ];
    volumes = [
      "/var/lib/authentik/certs:/certs:rw"
      "/var/lib/authentik/custom-templates:/templates:rw"
      "/var/lib/authentik/data:/data:rw"
    ];
    cmd = [ "worker" ];
    dependsOn = [
      "authentik-postgresql"
    ];
    user = "root";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=worker"
      "--network=authentik_default"
      "--shm-size=536870912"
    ];
  };
  systemd.services."podman-authentik-worker" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-authentik_default.service"
    ];
    requires = [
      "podman-network-authentik_default.service"
    ];
    partOf = [
      "podman-compose-authentik-root.target"
    ];
    wantedBy = [
      "podman-compose-authentik-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-authentik_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f authentik_default";
    };
    script = ''
      podman network inspect authentik_default || podman network create authentik_default
    '';
    partOf = [ "podman-compose-authentik-root.target" ];
    wantedBy = [ "podman-compose-authentik-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-authentik_database" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect authentik_database || podman volume create authentik_database --driver=local
    '';
    partOf = [ "podman-compose-authentik-root.target" ];
    wantedBy = [ "podman-compose-authentik-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-authentik-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
