# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-fcfa46e1-ca4f-42ee-9565-8d3e3053661b";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-fcfa46e1-ca4f-42ee-9565-8d3e3053661b".device = "/dev/disk/by-uuid/fcfa46e1-ca4f-42ee-9565-8d3e3053661b";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-fcfa46e1-ca4f-42ee-9565-8d3e3053661b";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-fcfa46e1-ca4f-42ee-9565-8d3e3053661b";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A194-413E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-7bee7b38-eff2-49f8-b996-130e4927a566"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
