# Initially auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  systemd.tmpfiles.rules = [
    "d /var/lib/comfymc 0755 root root -"
    "d /var/lib/comfymc/data 0755 root root -"
    "d /var/lib/comfymc/datapacks 0755 root root -"
    "d /var/lib/comfymc/mods 0755 root root -"
  ];

  virtualisation.oci-containers.backend = "podman";

  virtualisation.oci-containers.containers."mc-mc" = {
    image = "itzg/minecraft-server";
    environment = {
      "DATAPACKS" = "https://modrinth.com/datapack/kawamood-no-creeper-grief";
      "EULA" = "TRUE";
      "MAX_MEMORY" = "8G";
      "PACKWIZ_URL" = "https://waveringana.github.io/comfymc/pack.toml";
      "TYPE" = "NEOFORGE";
      "USE_MEOWICE_FLAGS" = "true";
      "VERSION" = "1.21.10";
    };
    volumes = [
      "/var/lib/comfymc/data:/data:rw"
      "/var/lib/comfymc/datapacks:/datapacks:rw"
      "/var/lib/comfymc/mods:/mods:rw"
    ];
    ports = [
      "25565:25565/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mc"
      "--network=mc_default"
    ];
  };
}
